version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./gestion-ecole-laravel-firebase.json:/var/www/gestion-ecole-laravel-firebase.json
    networks:
      - app-network
    depends_on:
      - db
      - postgres

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8845:80"  # Changé de 8844 à 8845
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: laravel_postgres
    environment:
      POSTGRES_USER: dame
      POSTGRES_PASSWORD: motivation
      POSTGRES_DB: gestion_ecole_laravel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  mysql_data:
  postgres_data:

networks:
  app-network:
    driver: bridge